### ISSUE TITLE
Flysystem adapter definition error message in 5.5.0

### ISSUE THREAD

**Issue by wluijt-endertech** [GregoireHebert/docusign-bundle#117]
After upgrading to 5.5.0, this error message appeared when clearing the Symfony cache:

```sh
$ php bin/console cache:clear

 // Clearing the cache for the dev environment with debug true                                                          


In DefinitionErrorExceptionPass.php line 54:
                                                                                                                                             
  Invalid constructor argument 3 for service "flysystem.adapter.default": argument 1 must be defined before. Check your service definition.  
                                                                                                                                             

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

```

Looking at the code, it seems like it is related to https://github.com/GregoireHebert/docusign-bundle/blob/5.5.0/src/Adapter/Builder/LocalAdapterDefinitionBuilder.php#L69 where arguments 0, 1, and 3 are defined after argument 2 in the conditional statements.  I suppose the argument 0 and argument 1 lines should be before the argument 2 conditional statements.

related https://github.com/GregoireHebert/docusign-bundle/pull/115
@GregoireHebert @vincentchalamon

**Comment by GregoireHebert** [comment]
Thanks @wluijt-endertech :)
